export default [
  {
    id: '1',
    type: 'task',
    data: {
      name: 'Setup Environment',
      description: 'Prepare the development environment by installing necessary tools and dependencies.',
      subtasks: [{ subtask: 'Install Node.js', isComplete: false }],
      connections: { up: null, down: 'source', left: null, right: null },
      isCompleted: false,
      createdAt: '2024-07-16T23:43:10.103Z',
      completedAt: null,
    },
    position: { x: 250, y: 5 },
  },
  {
    id: '2',
    type: 'task',
    data: {
      name: 'Database Design',
      description: 'Design the database schema for the project.',
      subtasks: [{ subtask: 'Create ER Diagram', isComplete: false }],
      connections: { up: 'target', down: 'source', left: null, right: null },
      isCompleted: false,
      createdAt: '2024-07-16T23:43:10.103Z',
      completedAt: null,
    },
    position: { x: 250, y: 150 },
  },
  {
    id: '3',
    type: 'task',
    data: {
      name: 'Build API',
      description: 'Develop the RESTful API endpoints for the application.',
      subtasks: [{ subtask: 'Implement Controllers', isComplete: false }],
      connections: { up: 'target', down: 'source', left: null, right: null },
      isCompleted: false,
      createdAt: '2024-07-16T23:43:10.103Z',
      completedAt: null,
    },
    position: { x: 250, y: 300 },
  },
  {
    id: '4',
    type: 'task',
    data: {
      name: 'Frontend Development',
      description: 'Create the user interface for the application using React.',
      subtasks: [{ subtask: 'Create Components', isComplete: false }],
      connections: { up: 'target', down: null, left: null, right: 'source' },
      isCompleted: false,
      createdAt: '2024-07-16T23:43:10.103Z',
      completedAt: null,
    },
    position: { x: 250, y: 450 },
  },
  {
    id: '5',
    type: 'task',
    data: {
      name: 'Testing & QA',
      description: 'Conduct thorough testing and quality assurance for the application.',
      subtasks: [{ subtask: 'Write Integration Tests', isComplete: false }],
      connections: { up: 'target', down: null, left: 'target', right: null },
      isCompleted: false,
      createdAt: '2024-07-16T23:43:10.103Z',
      completedAt: null,
    },
    position: { x: 500, y: 300 },
  },
];
