export default [
  {
    id: '1',
    type: 'task',
    data: {
      label: 'Start Node',
      title: <div>Start Here</div>,
      parentQuest: 'Main Quest',
      description: 'This is the start of the main quest.',
      subtasks: [],
      isCompleted: false,
      createdAt: new Date('2024-07-12T08:00:00Z').toISOString(),
      completedAt: null,
      connections: {
        up: { hasSocket: false, socketType: null },
        down: { hasSocket: true, socketType: 'src' },
        left: { hasSocket: false, socketType: null },
        right: { hasSocket: false, socketType: null },
      },
    },
    position: { x: 250, y: 25 },
  },
  {
    id: '2',
    type: 'task',
    data: {
      label: 'Task 1',
      title: <div>First Task</div>,
      parentQuest: 'Main Quest',
      description: 'This is the first task in the main quest.',
      subtasks: ['Subtask 1', 'Subtask 2'],
      isCompleted: false,
      createdAt: new Date('2024-07-12T09:00:00Z').toISOString(),
      completedAt: null,
      connections: {
        up: { hasSocket: true, socketType: 'target' },
        down: { hasSocket: true, socketType: 'src' },
        left: { hasSocket: false, socketType: null },
        right: { hasSocket: false, socketType: null },
      },
    },
    position: { x: 250, y: 125 },
  },
  {
    id: '3',
    type: 'task',
    data: {
      label: 'Task 2',
      title: <div>Second Task</div>,
      parentQuest: 'Main Quest',
      description: 'This is the second task in the main quest.',
      subtasks: ['Subtask A', 'Subtask B'],
      isCompleted: false,
      createdAt: new Date('2024-07-12T10:00:00Z').toISOString(),
      completedAt: null,
      connections: {
        up: { hasSocket: true, socketType: 'target' },
        down: { hasSocket: true, socketType: 'src' },
        left: { hasSocket: false, socketType: null },
        right: { hasSocket: false, socketType: null },
      },
    },
    position: { x: 250, y: 225 },
  },
  {
    id: '4',
    type: 'task',
    data: {
      label: 'Task 3',
      title: <div>Third Task</div>,
      parentQuest: 'Side Quest',
      description: 'This is a task in the side quest.',
      subtasks: [],
      isCompleted: false,
      createdAt: new Date('2024-07-12T11:00:00Z').toISOString(),
      completedAt: null,
      connections: {
        up: { hasSocket: true, socketType: 'target' },
        down: { hasSocket: true, socketType: 'src' },
        left: { hasSocket: false, socketType: null },
        right: { hasSocket: false, socketType: null },
      },
    },
    position: { x: 250, y: 325 },
  },
  {
    id: '5',
    type: 'task',
    data: {
      label: 'End Node',
      title: <div>End Here</div>,
      parentQuest: 'Main Quest',
      description: 'This is the end of the main quest.',
      subtasks: [],
      isCompleted: false,
      createdAt: new Date('2024-07-12T12:00:00Z').toISOString(),
      completedAt: null,
      connections: {
        up: { hasSocket: true, socketType: 'target' },
        down: { hasSocket: false, socketType: null },
        left: { hasSocket: false, socketType: null },
        right: { hasSocket: false, socketType: null },
      },
    },
    position: { x: 250, y: 425 },
  },
];
